### ISSUE TITLE
hang when retrieving MULTI..EXEC results

### ISSUE THREAD

**Issue by gregjor** [ziogas/PHP-Redis-implementation#2]
Ubuntu Linux 16.04, redis v 3.0.6, redis.php cloned from this repo.

The code below reliably hangs. If I remove the `MULTI` and `EXEC` it will work. It's hanging in the `multibulk_response()` function at the line `$tmp = trim(fgets($this->handle));`, it looks like it gets the first result but not the second one.

This works fine from the `redis-cli` command line tool.

```
<?php

require("redis.php");

$redis = new redis_cli('127.0.0.1', 6379);
$redis->cmd("MULTI")->cmd("INCR", "foo")->cmd("EXPIRE", "foo", 1)->cmd("EXEC")->set();
```

**Comment by ziogas** [comment]
Hello, which PHP version do you use?

**Comment by gregjor** [comment]
PHP 7.0.15

**Comment by ziogas** [comment]
Hello Greg,

I've made a few changes related with handling multibulk response and added few additional tests.
Seems that it works alright now, can you confirm this?

**Comment by gregjor** [comment]
Fixed. Thanks for quick response!
